### ISSUE TITLE
Design Docs Review #1

### ISSUE THREAD

**Issue by rlim92** [pauchye/ASTRA#1]
Hey Olga! Design docs lookin' good so far. Just a few tips and thoughts below.

**MVP List**
- [x] for saving workouts, starting from `perceived exertion` and down I would consider that to be bonus and do not worry about adding that until after the core 4 features are complete.
- [x] how is the workout feed generated? can be a simple algorithm or even just a normal database query.
- [x] what details exactly are shown in workout stats. Please be specific. 

**Schema**
- [x] for `routes` table the `url` column is unnecessary. If it refers to front-end routing, we can make the path in React. 
- [x] for the `workouts` table same as in MVP List consider adding the features of `perceived exertion` and below as bonus. 
- [x] Consider if there needs to be an association between the `routes` and `workouts`. If a workout uses multiple routes, it should show the routes the workout took. However, it looks like `workouts` can optionally use `routes`. I recommend a joins table joining `routes` and `workouts` so that `workouts` can have many `routes` and `routes` can be part of many `workouts`.

**Comment by pauchye** [comment]
Hi Rich, 
Please see below:
### MVP List:
1.  ok
2.  db query sorted by date rn. i will add some algorithm when i have followers (bonus)
3.  added. i don't expect to make it that far to be honest. basically there are details that we fill when we create a workout. + map, + pace chart as a bonus. 
### Schema:
1.  yes, i thought we might need a link to the google maps api. i replaced it with route data. i think we still need to store some info in the db (long, lat, etc). I don't really understand this part yet. it will be google maps api or mapbox. i will look into it on weekend.
2.  ok
3.  i added an association between routes and workouts (route has many workouts). 
Thank you.
