### ISSUE TITLE
Design Docs Review #3

### ISSUE THREAD

**Issue by rlim92** [pauchye/ASTRA#3]
Hey Olga! Routes are looking good. Suggestions below:

**Frontend Routes**
- [ ] `/workouts/workoutId/new` no need for this route as the previous route will take care of the new workout form. 

**Backend Routes**
- [ ] will need a user show route to get to `UserProfile`.
- nested route showing a user's route is good. 
- [ ] should add a regular `route index` route as well. This can be bonus later for `segments` but it looks like we can search for routes near our location. This would be a cool use of google Maps API too. 
- [ ] `GET /api/workouts` should nest this route and and include a `user_id` because one can see another's workouts on their profile.

**Comment by pauchye** [comment]
Frontend Routes:
1. updated it to be an edit route
Backend Routes:
1. i believe i have one `GET /api/users/:id` - user's show page (user's info and stats)
2. added but want to discuss. do we have 2 routes for routes index page?
3. updated it to be nested under user_id

**Comment by rlim92** [comment]
Hey Olga,

3. We should eventually have 2 routes because we should see our own routes we made and then we should see `segments` which look to be like public routes that one can take if they want. We can leave the second route for bonus.
